---
abstract: Utils
author:
  - 'Robert Acock <thisusedtobeanemail@gmail.com>'
build_requires:
  Moonshine::Test: '0.14'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Moonshine-Util
no_index:
  directory:
    - t
    - inc
provides:
  Moonshine::Util:
    file: lib/Moonshine/Util.pm
    version: '0.07'
requires:
  Exporter::Tiny: '0.044'
  HTML::Valid: '0.05'
  String::Elide::Parts: '0.07'
  String::Trim::More: '0.03'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  repository: https://github.com/ThisUsedToBeAnEmail/Moonshine-Util.git
version: '0.07'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
